=== RubenAC1999/Clase/LingMarc/Tema 4/ActividadLM4.7/ActividadLM4.7.1.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="listaPedidos">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="pedido" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="nombreCliente" type="xs:string"/>
                        <xs:element name="mesaEntrega">
                            <xs:simpleType>
                                <xs:restriction base="xs:positiveInteger">
                                    <xs:minInclusive value="1"/>
                                    <xs:maxInclusive value="13"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="fecha">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="dia" type="xs:positiveInteger" maxOccurs="31"/>
                                    <xs:element name="mes" type="xs:string"/>
                                    <xs:element name="anho" type="xs:positiveInteger"/>
                                    <xs:element name="hora" type="xs:string"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="listaProductos">
                            <xs:complexType> 
                                <xs:sequence>
                                    <xs:element name="producto" maxOccurs="unbounded">
                                        <xs:complexType>
                                            <xs:choice>
                                                <xs:element name="hamburguesa">
                                                    <xs:complexType>
                                                        <xs:sequence>
                                                            <xs:element name="nombre" >
                                                                <xs:complexType mixed="true">
                                                                    <xs:attribute name="codProducto" type="xs:string"/>
                                                                </xs:complexType>
                                                            </xs:element>
                                                            <xs:element name="numero" type="xs:positiveInteger"/>
                                                            <xs:element name="precio" type="xs:string"/>
                                                        </xs:sequence>
                                                    </xs:complexType>
                                                </xs:element>
                                                <xs:element name="complemento">
                                                    <xs:complexType>
                                                        <xs:sequence>
                                                            <xs:element name="nombre">
                                                                <xs:complexType mixed="true">
                                                                    <xs:attribute name="codProducto" type="xs:string"/>
                                                                </xs:complexType>
                                                            </xs:element>
                                                            <xs:element name="numero" type="xs:positiveInteger"/>
                                                            <xs:element name="precio" type="xs:string"/>
                                                        </xs:sequence>
                                                    </xs:complexType>
                                                </xs:element>
                                            </xs:choice>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="precioTotal" type="xs:string"/>
                    </xs:sequence>
                    <xs:attribute name="numPedido"> 
                        <xs:simpleType>
                            <xs:restriction base="xs:positiveInteger">
                                <xs:maxInclusive value="999"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>
</xs:schema>

=== RubenAC1999/Clase/LingMarc/Tema 4/ActividadLM4.7/ActividadLM4.7.1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>


<listaPedidos
xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
xs:noNamespaceSchemaLocation="ActividadLM4.7.1.xsd">

    <pedido numPedido="023">
        <nombreCliente> Rodrigo Goes </nombreCliente>
        <mesaEntrega> 8 </mesaEntrega>
        <fecha> 
            <dia> 10 </dia>
            <mes> Febrero </mes>
            <anho> 2024 </anho>
            <hora> 14:00 </hora>
        </fecha>
        <listaProductos>
            <producto>
                <hamburguesa>
                    <nombre codProducto="H303"> Burguer Cangreburguer </nombre>
                    <numero> 1 </numero>
                    <precio> 5.50 </precio>
                </hamburguesa>
            </producto>
            <producto>
                <complemento>
                    <nombre codProducto="P03"> Patatas deluxe </nombre>
                    <numero> 1 </numero>
                    <precio> 1.20 </precio>
                </complemento>
            </producto> 
        </listaProductos>
        <precioTotal> 6.70 </precioTotal>
    </pedido>
    <pedido numPedido="024">
        <nombreCliente> Eustaquio </nombreCliente>
        <fecha>
            <dia> 10 </dia>
            <mes> Febrero </mes>
            <anho> 2024 </anho>
            <hora> 14:15 </hora>
        </fecha>
        <listaProductos>
            <producto>
                <complemento>
                    <nombre codProducto="Hl10"> Helado con caramelo </nombre>
                    <numero> 1 </numero>
                    <precio> 1.70 </precio>
                </complemento>
            </producto>
        </listaProductos>
        <precioTotal> 1.70 </precioTotal>
    </pedido>
</listaPedidos>
