=== RubenAC1999/Clase/LingMarc/Tema 4/ActividadLM4.7/ActividadLM4.7.2.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="listaPedidos">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="direccionEnvio">
                <xs:complexType>
                    <xs:all>
                        <xs:element name="nombre" type="xs:string"/>
                        <xs:element name="apellidos" type="xs:string"/>
                        <xs:element name="calle" type="xs:string"/>
                        <xs:element name="numero" type="xs:positiveInteger"/>
                        <xs:element name="numPiso" type="xs:positiveInteger" minOccurs="0"/>
                        <xs:element name="letra" minOccurs="0">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:maxLength value="1"/>
                                    <xs:pattern value="[A-Z]"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="codigoPostal" type="xs:positiveInteger"/>
                        <xs:element name="ciudad" type="xs:string"/>
                        <xs:element name="comunidadAutonoma" type="xs:string"/>
                    </xs:all>
                </xs:complexType>
            </xs:element>
            <xs:element name="direccionFacturacion">
                <xs:complexType>
                    <xs:all>
                        <xs:element name="nombre" type="xs:string"/>
                        <xs:element name="apellidos" type="xs:string"/>
                        <xs:element name="calle" type="xs:string"/>
                        <xs:element name="numero" type="xs:positiveInteger"/>
                        <xs:element name="numPiso" type="xs:positiveInteger" minOccurs="0"/>
                        <xs:element name="letra" minOccurs="0">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:maxLength value="1"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="codigoPostal" type="xs:positiveInteger"/>
                        <xs:element name="ciudad" type="xs:string"/>
                        <xs:element name="comunidadAutonoma" type="xs:string"/>
                    </xs:all>
                </xs:complexType>
            </xs:element>
            <xs:element name="listaProductos">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="producto" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="nombre" type="xs:string"/>
                                    <xs:element name="cantidad" type="xs:positiveInteger"/>
                                    <xs:element name="precio">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:decimal">
                                                <xs:fractionDigits value="2"/>
                                                <xs:minInclusive value="0"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:element>
                                </xs:sequence>
                                <xs:attribute name="id">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:string">
                                            <xs:maxLength value="7"/>
                                            <xs:minLength value="7"/>
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:attribute>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="descuento" minOccurs="0">
                            <xs:simpleType>
                                <xs:restriction base="xs:decimal">
                                    <xs:fractionDigits value="2"/>
                                    <xs:maxInclusive value="0"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="precioTotal">
                            <xs:simpleType>
                                <xs:restriction base="xs:decimal">
                                    <xs:fractionDigits value="2"/>
                                    <xs:minInclusive value="0"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>
</xs:schema>

=== RubenAC1999/Clase/1DAM/LingMarc/Tema 4/ActividadLM4.7/ActividadLM4.7.2.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<listaPedidos xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
xs:noNamespaceSchemaLocation="ActividadLM4.7.2.xsd">

    <direccionEnvio>
        <nombre> José María </nombre>
        <apellidos> Gutiérrez Hernández </apellidos>
        <calle> Calle Santander </calle>
        <numero> 13 </numero>
        <numPiso> 2 </numPiso>
        <letra>D</letra>
        <codigoPostal> 15600 </codigoPostal>
        <ciudad> Santiago de Compostela </ciudad>
        <comunidadAutonoma> Galicia </comunidadAutonoma>
    </direccionEnvio>
    <direccionFacturacion>
        <nombre> José María </nombre>
        <apellidos> Gutiérrez Hernández </apellidos>
        <calle> Calle Santander </calle>
        <numero> 13 </numero>
        <numPiso> 2 </numPiso>
        <letra>D</letra>
        <codigoPostal> 15600 </codigoPostal>
        <ciudad> Santiago de Compostela </ciudad>
        <comunidadAutonoma> Galicia </comunidadAutonoma>
    </direccionFacturacion>
    <listaProductos>
        <producto id="E493319">
            <nombre> Producto1 </nombre>
            <cantidad> 2 </cantidad>
            <precio> 2.50 </precio>
        </producto>
        <producto id="R489448">
            <nombre> Producto2 </nombre>
            <cantidad> 1  </cantidad>
            <precio> 9.99 </precio> 
        </producto>
        <descuento> -2.00 </descuento>
        <precioTotal> 10.49 </precioTotal>
    </listaProductos>
</listaPedidos>
