=== RubenAC1999/Clase/LingMarc/Tema 4/ActividadLM4.7/ActividadLM4.7.3.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="horarioClase">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="dia" maxOccurs="5">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="sesion" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="hora">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:integer">
                                                <xs:minInclusive value="7"/>
                                                <xs:maxInclusive value="22"/>
                                             </xs:restriction>
                                        </xs:simpleType>
                                    </xs:element>
                                    <xs:element name="minutos">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value=" 00 "/>
                                                <xs:enumeration value=" 10 "/>
                                                <xs:enumeration value=" 20 "/>
                                                <xs:enumeration value=" 30 "/>
                                                <xs:enumeration value=" 40 "/>
                                                <xs:enumeration value=" 50 "/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:element>
                                    <xs:element name="asignatura" type="xs:string"/>
                                    <xs:element name="aula">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:positiveInteger">
                                                <xs:pattern value="[0-9]{3}"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:element>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    <xs:attribute name="nombre">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration value="Lunes"/>
                                <xs:enumeration value="Martes"/>
                                <xs:enumeration value="MiÃ©rcoles"/>
                                <xs:enumeration value="Jueves"/>
                                <xs:enumeration value="Viernes"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>

</xs:schema>

=== RubenAC1999/Clase/LingMarc/Tema 4/ActividadLM4.7/ActividadLM4.7.3.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<horarioClase xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
xs:noNamespaceSchemaLocation="ActividadLM4.7.3.xsd">

    <dia nombre="Lunes">
        <sesion>
            <hora> 15 </hora>
            <minutos> 30 </minutos>
            <asignatura> Bases de datos </asignatura>
            <aula> 105 </aula>
        </sesion>
        <sesion>
            <hora> 16 </hora>
            <minutos> 20 </minutos>
            <asignatura> Bases de datos </asignatura>
            <aula> 112 </aula>
        </sesion>
        <sesion>
            <hora> 17 </hora>
            <minutos> 30 </minutos>
            <asignatura> Bases de datos </asignatura>
            <aula> 112 </aula>
        </sesion>
        <sesion>
            <hora> 18 </hora>
            <minutos> 20 </minutos>
            <asignatura> Lenguajes de marcas y sistemas de gestión de información </asignatura>
            <aula> 112 </aula>
        </sesion>
        <sesion>
            <hora> 19 </hora>
            <minutos> 10 </minutos>
            <asignatura> Lenguaje de marcas y sistemas de gestión de información </asignatura>
            <aula> 112 </aula>
        </sesion>
        <sesion>
            <hora> 20 </hora>
            <minutos> 20 </minutos>
            <asignatura> Sistemas informáticos </asignatura>
            <aula> 112 </aula>
        </sesion>
        <sesion>
            <hora> 21 </hora>
            <minutos> 10 </minutos>
            <asignatura> Sistemas informáticos </asignatura>
            <aula> 112 </aula>
        </sesion>
    </dia>

    <dia nombre="Martes"> 
        <sesion>
            <hora> 16 </hora>
            <minutos> 20 </minutos>
            <asignatura> Sistemas informáticos </asignatura>
            <aula> 112 </aula>
        </sesion>
        <sesion>
            <hora> 17 </hora>
            <minutos> 30 </minutos>
            <asignatura> Sistemas informáticos </asignatura>
            <aula> 112 </aula>
        </sesion>
        <sesion>
            <hora> 18 </hora>
            <minutos> 20 </minutos>
            <asignatura> Sistemas informáticos </asignatura>
            <aula> 112 </aula>
        </sesion>
        <sesion>
            <hora> 19 </hora>
            <minutos> 10 </minutos>
            <asignatura> Bases de datos </asignatura>
            <aula> 112 </aula>
        </sesion>
        <sesion>
            <hora> 20 </hora>
            <minutos> 20 </minutos>
            <asignatura> Programación </asignatura>
            <aula> 112 </aula>
        </sesion>
        <sesion>
            <hora> 21 </hora>
            <minutos> 10 </minutos>
            <asignatura> Programación </asignatura>
            <aula> 112 </aula>
        </sesion>
    </dia>

    <dia nombre="Miércoles"> 
        <sesion>
            <hora> 16 </hora>
            <minutos> 20 </minutos>
            <asignatura> Bases de datos </asignatura>
            <aula> 112 </aula>
        </sesion>
        <sesion>
            <hora> 17 </hora>
            <minutos> 30 </minutos>
            <asignatura> Programación </asignatura>
            <aula> 112 </aula>
        </sesion>
        <sesion>
            <hora> 18 </hora>
            <minutos> 20 </minutos>
            <asignatura> Programación </asignatura>
            <aula> 112 </aula>
        </sesion>
        <sesion>
            <hora> 19 </hora>
            <minutos> 10 </minutos>
            <asignatura> Programación </asignatura>
            <aula> 112 </aula>
        </sesion>
        <sesion>
            <hora> 20 </hora>
            <minutos> 20 </minutos>
            <asignatura> Contornos de desarrollo </asignatura>
            <aula> 112 </aula>
        </sesion>
        <sesion>
            <hora> 21 </hora>
            <minutos> 10 </minutos>
            <asignatura> Contornos de desarrollo </asignatura>
            <aula> 112 </aula>
        </sesion>
    </dia>

    <dia nombre="Jueves">
        <sesion>
            <hora> 14 </hora>
            <minutos> 40 </minutos>
            <asignatura> Lenguaje de marcas y sistemas de gestión de información </asignatura>
            <aula> 105 </aula>
        </sesion>
        <sesion>
            <hora> 15 </hora>
            <minutos> 30 </minutos>
            <asignatura> Lenguajes de marcas y sistemas de gestión de información </asignatura>
            <aula> 105 </aula>
        </sesion> 
        <sesion>
            <hora> 16 </hora>
            <minutos> 20 </minutos>
            <asignatura> Bases de datos </asignatura>
            <aula> 112 </aula>
        </sesion>
        <sesion>
            <hora> 17 </hora>
            <minutos> 30 </minutos>
            <asignatura> Bases de datos </asignatura>
            <aula> 112 </aula>
        </sesion>
        <sesion>
            <hora> 18 </hora>
            <minutos> 20 </minutos>
            <asignatura> Contornos de desarrollo </asignatura>
            <aula> 112 </aula>
        </sesion>
        <sesion>
            <hora> 19 </hora>
            <minutos> 10 </minutos>
            <asignatura> Programación </asignatura>
            <aula> 112 </aula>
        </sesion>
        <sesion>
            <hora> 20 </hora>
            <minutos> 20 </minutos>
            <asignatura> Programación </asignatura>
            <aula> 112 </aula>
        </sesion>
        <sesion>
            <hora> 21 </hora>
            <minutos> 10 </minutos>
            <asignatura> Programación </asignatura>
            <aula> 112 </aula>
        </sesion>
    </dia>

    <dia nombre="Viernes">
        <sesion>
            <hora> 17 </hora>
            <minutos> 30 </minutos>
            <asignatura> Lenguaje de marcas y sistemas de gestión de información </asignatura>
            <aula> 112 </aula>
        </sesion>
        <sesion>
            <hora> 18 </hora>
            <minutos> 20 </minutos>
            <asignatura> Programación </asignatura>
            <aula> 112 </aula>
        </sesion>
        <sesion>
            <hora> 19 </hora>
            <minutos> 10 </minutos>
            <asignatura> Contornos de desarrollo </asignatura>
            <aula> 112 </aula>
        </sesion>
        <sesion>
            <hora> 20 </hora>
            <minutos> 20 </minutos>
            <asignatura> Sistemas informáticos </asignatura>
            <aula> 112 </aula>
        </sesion>
        <sesion>
            <hora> 21 </hora>
            <minutos> 10 </minutos>
            <asignatura> Sistemas informáticos </asignatura>
            <aula> 112 </aula>
        </sesion>
    </dia>
</horarioClase>
