=== RubenAC1999/Clase/1DAM/LingMarc/Tema 4/ActividadLM4.5/Agra_Casal_Ruben_LM42.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="viaje">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nombre" type="xs:string"/>
                <xs:element name="apellidos" type="xs:string"/>
                <xs:element name="fechaInicio" type="xs:date"/>
                <xs:element name="fechaFin" type="xs:date"/>
                <xs:element name="origenViaje" type="xs:string"/>
                <xs:element name="relacionDestinos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="destino" maxOccurs="unbounded">
                                <xs:complexType>  
                                    <xs:sequence>
                                        <xs:element name="nombreCiudad" type="xs:string"/>
                                        <xs:element name="nombreHotel"  type="xs:string"/>
                                        <xs:element name="numeroNoches" type="xs:integer"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="precioViaje" type="xs:string"/>
           </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== RubenAC1999/Clase/LingMarc/Tema 4/Agra_Casal_Ruben_LM42.xml
<?xml version="1.0" encoding="UTF-8" ?>

<viaje 
xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
xs:noNamespaceSchemaLocation="Agra_Casal_Ruben_LM42.xsd">
	<nombre> Paco </nombre>
	<apellidos> Gutiérrez Fernández </apellidos>
	<fechaInicio> 2024-02-02 </fechaInicio>
	<fechaFin> 2024-09-02 </fechaFin>
	<origenViaje> Francia </origenViaje>
	<relacionDestinos>
        <destino>
		    <nombreCiudad> París </nombreCiudad>
		    <nombreHotel> Hotel Stars </nombreHotel>
		    <numeroNoches> 7 </numeroNoches>
        </destino>
	</relacionDestinos>
	<precioViaje> 1000 € </precioViaje>
</viaje>
