<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE famosos [
<!ELEMENT famosos (famoso+)>
<!ELEMENT famoso (nombre, apodo*, fechaNacimiento?, profesion*)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apodo (#PCDATA)>
<!ELEMENT profesion (#PCDATA)>
<!ELEMENT fechaNacimiento (#PCDATA)>
]>

<famosos>
    <famoso>
        <nombre>Michael Jackson</nombre>
        <apodo>El rey del pop</apodo>
        <profesion>cantante</profesion>
    </famoso>
    <famoso>
        <nombre>Frank Sinatra</nombre>
        <apodo>La voz</apodo>
        <fechaNacimiento>12-dec-1915</fechaNacimiento>
        <profesion>cantante</profesion>
        <profesion>actor</profesion>
    </famoso>
</famosos>