=== RubenAC1999/Clase/1DAM/LingMarc/EjerciciosRepaso/EjercicioRepaso4.2.dtd
<!ELEMENT viaje (nombre, apellidos, fechaInicio, fechaFin, origen, relacionDestinos, precioViaje)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT fechaInicio (#PCDATA)>
<!ELEMENT fechaFin (#PCDATA)>
<!ELEMENT origen (#PCDATA)>
<!ELEMENT relacionDestinos (destino+)>
<!ELEMENT destino (ciudad, hotel+, numNoches)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT hotel (#PCDATA)>
<!ELEMENT numNoches (#PCDATA)>
<!ELEMENT precioViaje (#PCDATA)>

=== RubenAC1999/Clase/LingMarc/EjerciciosRepaso/EjercicioRepaso4.2.xml
<?xml version= "1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE viaje SYSTEM "EjercicioRepaso4.2.dtd">

 <viaje>
    <nombre> Cliente </nombre>
    <apellidos> ApellidosCliente </apellidos>
    <fechaInicio> 11/12/2020 </fechaInicio>
    <fechaFin> 03/01/2021 </fechaFin>
    <origen> Madrid </origen>
    <relacionDestinos>
        <destino>
            <ciudad> nombreCiudad </ciudad>
            <hotel> nombreHotel </hotel>
            <numNoches> 3 </numNoches>
        </destino>
        <destino> 
            <ciudad> nombreCiudad </ciudad>
            <hotel> nombreHotel2 </hotel>
            <numNoches> 3 </numNoches>
        </destino>
    </relacionDestinos>
    <precioViaje> 1000 â‚¬ </precioViaje>
 </viaje>
