=== RubenAC1999/Clase/LingMarc/Tema 4/ActividadLM4.6/ActividadLM4.6.2.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="clases">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="clase" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="aula" type="xs:integer"/>
                            <xs:element name="grupo" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="codigo" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== RubenAC1999/Clase/1DAM/LingMarc/Tema 4/ActividadLM4.6/ActividadLM4.6.2.xml
<?xml version="1.0" encoding="UTF-8"?>

<clases
xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
xs:noNamespaceSchemaLocation="ActividadLM4.6.2.xsd">

    <clase codigo="LM2DAMORD2324">
        <nombre>Lenguajes de marcas</nombre>
        <aula>112</aula>
        <grupo>1ยบ DAM</grupo>
    </clase>
    <clase codigo="BD2DAMORD2324">
        <nombre>Base de datos</nombre>
        <aula>112</aula>
        <grupo>1ยบ DAM</grupo>
    </clase>
</clases>
