=== RubenAC1999/Clase/LingMarc/Tema 4/Actividad LM4.3/Ejercicio2.dtd
<!ENTITY grupo "1ยบ DAM">

<!ELEMENT clases (clase+)>
<!ELEMENT clase (nombre, aula, grupo)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT aula (#PCDATA)>
<!ELEMENT grupo (#PCDATA)>

<!ATTLIST clase codigo ID #REQUIRED>

=== RubenAC1999/Clase/1DAM/LingMarc/Tema 4/Actividad LM4.3/Ejercicio2.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE clases SYSTEM "Ejercicio2.dtd">
<clases>
    <clase codigo="LM2DAMORD2324">
        <nombre>Lenguajes de marcas</nombre>
        <aula>112</aula>
        <grupo>&grupo;</grupo>
    </clase>
    <clase codigo="BD2DAMORD2324">
        <nombre>Base de datos</nombre>
        <aula>112</aula>
        <grupo>&grupo;</grupo>
    </clase>
</clases>
